### ISSUE TITLE
add React to the project

### ISSUE THREAD

**Issue by MasterIfeanyi** [MasterIfeanyi/My-own-quiz-game#1]
Currently, the project is written with HTML, CSS and vanilla JavaScript. I would love to convert the project to a React  based project.

If you can write unit tests too, **go for it** 😉

**Comment by gokhalevedant06** [comment]
Hi @MasterIfeanyi, I would like to work on this issue

**Comment by MasterIfeanyi** [comment]
Go for it, I hope you understand the issue.

**Comment by gokhalevedant06** [comment]
Yes. Could you please assign it to me ?

**Comment by gaurav-iitb** [comment]
hey @MasterIfeanyi could you please assign this to me
