### ISSUE TITLE
Randomize the questions and answers

### ISSUE THREAD

**Issue by mateusabelli** [MasterIfeanyi/My-own-quiz-game#12]
Currently the questions and answers follows the same sequential order, after playing for a while it's possible to memorize the answers.

I would like to implement a randomization function that prevents that by generating random array positions each time the users begin playing. If you find this helpful please consider assigning me.

**Comment by MasterIfeanyi** [comment]
@mateusabelli Yes, please do, I would love it.

**Comment by mateusabelli** [comment]
That's great @MasterIfeanyi, do you mind assigning me for this issue with a hacktober label?
