### ISSUE TITLE
Add Netlify redirects

### ISSUE THREAD

**Issue by MasterIfeanyi** [MasterIfeanyi/My-own-quiz-game#3]
This is a React app and I would love to add a `redirects` file. Read this [blog](https://www.alexnielsen.net/old-blog//uncategorized/how-to-fix-netlify-page-not-found-broken-link-or-entered-a-url-that-doesnt-exist-error/)

**Comment by Hritik-Verma41** [comment]
i want to do this asign me

**Comment by MasterIfeanyi** [comment]
Thank you. Go for it.

**Comment by Hritik-Verma41** [comment]
working on it

**Comment by Hritik-Verma41** [comment]
added check and merge please
