### ISSUE TITLE
Add better Readme

### ISSUE THREAD

**Issue by MasterIfeanyi** [MasterIfeanyi/My-own-quiz-game#4]
Can you write a well-documented readme ?

The readme should follow the same pattern as this github [readme](https://github.com/MasterIfeanyi/ifeanyi-advice)

**Comment by aswin2108** [comment]
I would like to take on this issue! pls Assign it to me!

**Comment by MasterIfeanyi** [comment]
Thank you. Go for it.

**Comment by Pakhi-v** [comment]
@MasterIfeanyi what else changes you want with readme? Please let me know I will make.

**Comment by MasterIfeanyi** [comment]
@Pakhi-v No, not all Thank you. I forgot to close this issue.
